### ISSUE TITLE
Highlight error for string arguments of attributes that contains close bracket

### ISSUE THREAD

**Issue by defuz** [jhasse/sublime-rust#37] opened 2015-02-19 15:22 UTC
It seems like the bracket closes the attribute even if it is part of the string:

![screenshot 2015-02-19 17 18 10](https://cloud.githubusercontent.com/assets/276041/6269389/85f1b830-b85b-11e4-97d8-f42615ba47a6.png)

**Comment by rprichard** [comment] 2015-03-13 08:33
Duplicate of #24

**Closed** 2015-03-13 10:24 UTC
